//! Deployment backend abstraction for running composed sandboxes on any target.
//!
//! The forge pipeline produces a composed environment + bridge policy + attestation.
//! This module translates that into deployment specifications for different targets:
//!
//! - **Local**: direct syscalls via gleisner-polis (current behavior)
//! - **GCP**: Cloud Run Jobs or Confidential VMs
//! - **AWS**: Fargate tasks or Nitro Enclave instances
//!
//! The output of [`generate_deploy_spec`] is a [`DeploySpec`] containing both
//! structured configuration and executable shell commands. A management Claude
//! can read the spec to understand what will happen, then execute the commands
//! (or pass them to the user for review).

use std::fmt::Write as _;

use crate::bridge::BridgeReport;

/// Deployment target for running a composed sandbox.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(tag = "target", rename_all = "lowercase")]
pub enum DeployTarget {
    /// Run locally using direct syscalls (current behavior).
    Local,
    /// Deploy to Google Cloud Platform.
    Gcp(GcpConfig),
    /// Deploy to Amazon Web Services.
    Aws(AwsConfig),
}

/// GCP deployment configuration.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GcpConfig {
    /// GCP project ID.
    pub project: String,
    /// GCP region (e.g., "us-central1").
    pub region: String,
    /// Compute tier: `cloud-run` (default, serverless) or `compute-engine` (VMs).
    #[serde(default = "default_gcp_service")]
    pub service: GcpService,
    /// Machine type for Compute Engine (e.g., "e2-standard-4").
    pub machine_type: Option<String>,
    /// GCS bucket for manifest + artifact storage.
    pub bucket: String,
    /// Enable Confidential VM (AMD SEV-SNP attestation).
    #[serde(default)]
    pub confidential: bool,
    /// Service account email (uses default if unset).
    pub service_account: Option<String>,
}

/// GCP service to deploy on.
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum GcpService {
    /// Cloud Run Jobs (serverless, simplest).
    #[default]
    CloudRun,
    /// Compute Engine VM (more control, Confidential VM available).
    ComputeEngine,
}

/// AWS deployment configuration.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct AwsConfig {
    /// AWS region (e.g., "us-east-1").
    pub region: String,
    /// Compute tier: `fargate` (default, serverless) or `ec2` (instances).
    #[serde(default = "default_aws_service")]
    pub service: AwsService,
    /// Instance type for EC2 (e.g., "c6a.xlarge").
    pub instance_type: Option<String>,
    /// S3 bucket for manifest + artifact storage.
    pub bucket: String,
    /// Enable Nitro Enclaves (hardware attestation).
    #[serde(default)]
    pub nitro_enclave: bool,
    /// IAM role ARN (uses task execution role if unset).
    pub iam_role: Option<String>,
}

/// AWS service to deploy on.
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum AwsService {
    /// Fargate (serverless containers, simplest).
    #[default]
    Fargate,
    /// EC2 instance (more control, Nitro Enclaves available).
    Ec2,
}

/// Everything needed to deploy a forge session to any target.
///
/// Generated by [`generate_deploy_spec`] and consumed by the CLI or a
/// management Claude. Contains both machine-readable configuration and
/// human/Claude-readable shell commands.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DeploySpec {
    /// Which target this spec deploys to.
    pub target: DeployTarget,
    /// URI where the session manifest will be written after completion.
    ///
    /// - Local: `file:///path/to/.gleisner/session-manifest.json`
    /// - GCP: `gs://bucket/sessions/{id}/manifest.json`
    /// - AWS: `s3://bucket/sessions/{id}/manifest.json`
    pub manifest_uri: String,
    /// URI where the forge output JSON is stored for the inner Claude to reference.
    pub forge_uri: String,
    /// Volume/bind mount mappings for the target platform.
    pub volumes: Vec<VolumeMount>,
    /// Network configuration for the target platform.
    pub network: NetworkSpec,
    /// Shell commands to execute this deployment.
    ///
    /// A management Claude can inspect these, understand them, and execute
    /// them directly. Each command includes a comment explaining its purpose.
    pub commands: Vec<DeployCommand>,
    /// Environment variables to set in the deployed container/VM.
    pub env_vars: Vec<EnvVar>,
}

/// A volume mount for the target platform.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct VolumeMount {
    /// Source (host path, GCS path, or S3 path).
    pub source: String,
    /// Mount point inside the container/VM.
    pub mount_path: String,
    /// Read-only mount.
    pub read_only: bool,
}

/// Network configuration for the target platform.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct NetworkSpec {
    /// Whether DNS is allowed.
    pub allow_dns: bool,
    /// Whether outbound internet is allowed.
    pub allow_internet: bool,
    /// VPC connector or security group name (if applicable).
    pub vpc_config: Option<String>,
}

/// A shell command with an explanation.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DeployCommand {
    /// What this command does (human/Claude-readable).
    pub description: String,
    /// The shell command to execute.
    pub command: String,
}

/// An environment variable for the container/VM.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct EnvVar {
    /// Variable name.
    pub name: String,
    /// Variable value.
    pub value: String,
}

/// Input for generating a deploy spec.
pub struct DeployInput<'a> {
    /// The forge output JSON (environment + attestation).
    pub forge_json: &'a serde_json::Value,
    /// The bridge report (filesystem/network policy).
    pub report: &'a BridgeReport,
    /// Project directory to mount in the sandbox.
    pub project_dir: &'a std::path::Path,
    /// Claude Code binary/image identifier.
    pub claude_image: &'a str,
    /// Additional arguments for Claude Code.
    pub claude_args: &'a [String],
    /// Session identifier (for manifest paths).
    pub session_id: &'a str,
}

/// Generate a deployment specification for the given target.
///
/// This produces a complete [`DeploySpec`] containing volume mappings,
/// network config, environment variables, and executable shell commands.
/// The management Claude uses this to understand and execute the deployment.
pub fn generate_deploy_spec(target: &DeployTarget, input: &DeployInput<'_>) -> DeploySpec {
    match target {
        DeployTarget::Local => generate_local_spec(input),
        DeployTarget::Gcp(config) => generate_gcp_spec(config, input),
        DeployTarget::Aws(config) => generate_aws_spec(config, input),
    }
}

fn generate_local_spec(input: &DeployInput<'_>) -> DeploySpec {
    let mut volumes = Vec::new();
    let mut commands = Vec::new();

    // Project directory is always mounted RW
    volumes.push(VolumeMount {
        source: input.project_dir.display().to_string(),
        mount_path: input.project_dir.display().to_string(),
        read_only: false,
    });

    // Add forge-declared binds
    for path in &input.report.filesystem.readonly_bind {
        volumes.push(VolumeMount {
            source: path.display().to_string(),
            mount_path: path.display().to_string(),
            read_only: true,
        });
    }
    for path in &input.report.filesystem.readwrite_bind {
        volumes.push(VolumeMount {
            source: path.display().to_string(),
            mount_path: path.display().to_string(),
            read_only: false,
        });
    }

    let manifest_path = input
        .project_dir
        .join(".gleisner")
        .join("session-manifest.json");

    // Build the gleisner forge --run command
    let cmd_parts = [
        "gleisner".to_string(),
        "forge".to_string(),
        "--run".to_string(),
    ];
    // The actual pkgs-dir, stdlib-dir etc. come from the forge JSON — the local
    // backend just re-runs `gleisner forge --run` with the same args.
    commands.push(DeployCommand {
        description: "Run Claude Code in a local sandbox with the composed forge environment"
            .to_string(),
        command: cmd_parts.join(" "),
    });

    DeploySpec {
        target: DeployTarget::Local,
        manifest_uri: format!("file://{}", manifest_path.display()),
        forge_uri: format!(
            "file://{}",
            input
                .project_dir
                .join(".gleisner/composed-env.json")
                .display()
        ),
        volumes,
        network: NetworkSpec {
            allow_dns: input.report.network.allow_dns,
            allow_internet: input.report.network.allow_internet,
            vpc_config: None,
        },
        commands,
        env_vars: vec![],
    }
}

fn generate_gcp_spec(config: &GcpConfig, input: &DeployInput<'_>) -> DeploySpec {
    let session_prefix = format!("sessions/{}", input.session_id);
    let manifest_uri = format!("gs://{}/{session_prefix}/manifest.json", config.bucket);
    let forge_uri = format!("gs://{}/{session_prefix}/forge-output.json", config.bucket);
    let project_mount = format!("gs://{}/{session_prefix}/project", config.bucket);

    let mut volumes = Vec::new();
    let mut commands = Vec::new();
    let mut env_vars = vec![
        EnvVar {
            name: "GLEISNER_SESSION_ID".to_string(),
            value: input.session_id.to_string(),
        },
        EnvVar {
            name: "GLEISNER_MANIFEST_URI".to_string(),
            value: manifest_uri.clone(),
        },
        EnvVar {
            name: "GLEISNER_FORGE_URI".to_string(),
            value: forge_uri.clone(),
        },
    ];

    // Project volume
    volumes.push(VolumeMount {
        source: project_mount.clone(),
        mount_path: "/workspace".to_string(),
        read_only: false,
    });

    // Map forge filesystem policy to GCS-backed volumes
    for (i, path) in input.report.filesystem.readonly_bind.iter().enumerate() {
        volumes.push(VolumeMount {
            source: format!(
                "gs://{bucket}/{session_prefix}/ro-{i}",
                bucket = config.bucket
            ),
            mount_path: path.display().to_string(),
            read_only: true,
        });
    }
    for (i, path) in input.report.filesystem.readwrite_bind.iter().enumerate() {
        volumes.push(VolumeMount {
            source: format!(
                "gs://{bucket}/{session_prefix}/rw-{i}",
                bucket = config.bucket
            ),
            mount_path: path.display().to_string(),
            read_only: false,
        });
    }

    // Step 1: Upload forge output to GCS
    commands.push(DeployCommand {
        description: "Upload forge output JSON to GCS for the inner Claude to reference"
            .to_string(),
        command: format!(
            "echo '{}' | gsutil cp - {forge_uri}",
            // In practice the management Claude would pipe the actual JSON
            "${FORGE_OUTPUT_JSON}"
        ),
    });

    // Step 2: Sync project directory
    commands.push(DeployCommand {
        description: "Sync project directory to GCS".to_string(),
        command: format!(
            "gsutil -m rsync -r {} {project_mount}",
            input.project_dir.display()
        ),
    });

    match config.service {
        GcpService::CloudRun => {
            generate_gcp_cloudrun_commands(config, input, &env_vars, &mut commands);
        }
        GcpService::ComputeEngine => {
            generate_gcp_vm_commands(config, input, &env_vars, &mut commands);
        }
    }

    // Final step: Retrieve manifest
    commands.push(DeployCommand {
        description: "Retrieve the session manifest after completion".to_string(),
        command: format!("gsutil cat {manifest_uri}"),
    });

    // Network config
    let vpc_config = if input.report.network.allow_internet {
        Some("default-vpc-connector".to_string())
    } else {
        None
    };

    if let Some(sa) = &config.service_account {
        env_vars.push(EnvVar {
            name: "GLEISNER_SERVICE_ACCOUNT".to_string(),
            value: sa.clone(),
        });
    }

    DeploySpec {
        target: DeployTarget::Gcp(config.clone()),
        manifest_uri,
        forge_uri,
        volumes,
        network: NetworkSpec {
            allow_dns: input.report.network.allow_dns,
            allow_internet: input.report.network.allow_internet,
            vpc_config,
        },
        commands,
        env_vars,
    }
}

fn generate_gcp_cloudrun_commands(
    config: &GcpConfig,
    input: &DeployInput<'_>,
    env_vars: &[EnvVar],
    commands: &mut Vec<DeployCommand>,
) {
    let job_name = format!("gleisner-{}", input.session_id);
    let env_str: String = env_vars
        .iter()
        .map(|e| format!("{}={}", e.name, e.value))
        .collect::<Vec<_>>()
        .join(",");

    let mut create_cmd = format!(
        "gcloud run jobs create {job_name} \
         --project={project} \
         --region={region} \
         --image=gleisner-sandbox:latest \
         --set-env-vars='{env_str}' \
         --task-timeout=3600s \
         --max-retries=0",
        project = config.project,
        region = config.region,
    );

    if !input.report.network.allow_internet {
        create_cmd.push_str(" --no-vpc-egress");
    }

    if let Some(sa) = &config.service_account {
        let _ = write!(create_cmd, " --service-account={sa}");
    }

    commands.push(DeployCommand {
        description: "Create a Cloud Run Job with the forge sandbox configuration".to_string(),
        command: create_cmd,
    });

    commands.push(DeployCommand {
        description: "Execute the Cloud Run Job".to_string(),
        command: format!(
            "gcloud run jobs execute {job_name} --project={} --region={} --wait",
            config.project, config.region,
        ),
    });
}

fn generate_gcp_vm_commands(
    config: &GcpConfig,
    input: &DeployInput<'_>,
    env_vars: &[EnvVar],
    commands: &mut Vec<DeployCommand>,
) {
    let vm_name = format!("gleisner-{}", input.session_id);
    let machine_type = config.machine_type.as_deref().unwrap_or("e2-standard-4");

    let metadata_items: String = env_vars
        .iter()
        .map(|e| format!("{}={}", e.name, e.value))
        .collect::<Vec<_>>()
        .join(",");

    let mut create_cmd = format!(
        "gcloud compute instances create {vm_name} \
         --project={project} \
         --zone={region}-a \
         --machine-type={machine_type} \
         --image-family=debian-12 \
         --image-project=debian-cloud \
         --metadata={metadata_items} \
         --scopes=storage-rw",
        project = config.project,
        region = config.region,
    );

    if config.confidential {
        create_cmd.push_str(
            " --confidential-compute-type=SEV_SNP \
             --min-cpu-platform='AMD Milan'",
        );
    }

    if let Some(sa) = &config.service_account {
        let _ = write!(create_cmd, " --service-account={sa}");
    }

    if !input.report.network.allow_internet {
        create_cmd.push_str(" --no-address");
    }

    commands.push(DeployCommand {
        description: format!(
            "Create a {} Compute Engine VM",
            if config.confidential {
                "Confidential"
            } else {
                "standard"
            }
        ),
        command: create_cmd,
    });

    commands.push(DeployCommand {
        description: "SSH in and run the gleisner sandbox".to_string(),
        command: format!(
            "gcloud compute ssh {vm_name} --project={} --zone={}-a -- \
             'curl -fsSL https://gleisner.dev/install.sh | bash && \
              gsutil cp ${{GLEISNER_FORGE_URI}} /tmp/forge-output.json && \
              gleisner forge --run --from-spec /tmp/forge-output.json && \
              gsutil cp .gleisner/session-manifest.json ${{GLEISNER_MANIFEST_URI}}'",
            config.project, config.region,
        ),
    });

    commands.push(DeployCommand {
        description: "Delete the VM after session completes".to_string(),
        command: format!(
            "gcloud compute instances delete {vm_name} --project={} --zone={}-a --quiet",
            config.project, config.region,
        ),
    });
}

fn generate_aws_spec(config: &AwsConfig, input: &DeployInput<'_>) -> DeploySpec {
    let session_prefix = format!("sessions/{}", input.session_id);
    let manifest_uri = format!("s3://{}/{session_prefix}/manifest.json", config.bucket);
    let forge_uri = format!("s3://{}/{session_prefix}/forge-output.json", config.bucket);
    let project_mount = format!("s3://{}/{session_prefix}/project", config.bucket);

    let mut volumes = Vec::new();
    let mut commands = Vec::new();
    let mut env_vars = vec![
        EnvVar {
            name: "GLEISNER_SESSION_ID".to_string(),
            value: input.session_id.to_string(),
        },
        EnvVar {
            name: "GLEISNER_MANIFEST_URI".to_string(),
            value: manifest_uri.clone(),
        },
        EnvVar {
            name: "GLEISNER_FORGE_URI".to_string(),
            value: forge_uri.clone(),
        },
        EnvVar {
            name: "AWS_DEFAULT_REGION".to_string(),
            value: config.region.clone(),
        },
    ];

    // Project volume
    volumes.push(VolumeMount {
        source: project_mount.clone(),
        mount_path: "/workspace".to_string(),
        read_only: false,
    });

    for (i, path) in input.report.filesystem.readonly_bind.iter().enumerate() {
        volumes.push(VolumeMount {
            source: format!(
                "s3://{bucket}/{session_prefix}/ro-{i}",
                bucket = config.bucket
            ),
            mount_path: path.display().to_string(),
            read_only: true,
        });
    }
    for (i, path) in input.report.filesystem.readwrite_bind.iter().enumerate() {
        volumes.push(VolumeMount {
            source: format!(
                "s3://{bucket}/{session_prefix}/rw-{i}",
                bucket = config.bucket
            ),
            mount_path: path.display().to_string(),
            read_only: false,
        });
    }

    // Upload forge output
    commands.push(DeployCommand {
        description: "Upload forge output JSON to S3".to_string(),
        command: format!("aws s3 cp - {forge_uri} <<< \"${{FORGE_OUTPUT_JSON}}\""),
    });

    // Sync project
    commands.push(DeployCommand {
        description: "Sync project directory to S3".to_string(),
        command: format!(
            "aws s3 sync {} {project_mount}",
            input.project_dir.display()
        ),
    });

    match config.service {
        AwsService::Fargate => {
            generate_aws_fargate_commands(config, input, &env_vars, &mut commands);
        }
        AwsService::Ec2 => {
            generate_aws_ec2_commands(config, input, &env_vars, &mut commands);
        }
    }

    // Retrieve manifest
    commands.push(DeployCommand {
        description: "Retrieve the session manifest after completion".to_string(),
        command: format!("aws s3 cp {manifest_uri} -"),
    });

    if let Some(role) = &config.iam_role {
        env_vars.push(EnvVar {
            name: "GLEISNER_IAM_ROLE".to_string(),
            value: role.clone(),
        });
    }

    let vpc_config = if input.report.network.allow_internet {
        None // Default VPC allows outbound
    } else {
        Some("gleisner-isolated-sg".to_string())
    };

    DeploySpec {
        target: DeployTarget::Aws(config.clone()),
        manifest_uri,
        forge_uri,
        volumes,
        network: NetworkSpec {
            allow_dns: input.report.network.allow_dns,
            allow_internet: input.report.network.allow_internet,
            vpc_config,
        },
        commands,
        env_vars,
    }
}

fn generate_aws_fargate_commands(
    config: &AwsConfig,
    input: &DeployInput<'_>,
    env_vars: &[EnvVar],
    commands: &mut Vec<DeployCommand>,
) {
    let task_name = format!("gleisner-{}", input.session_id);
    let env_overrides: Vec<String> = env_vars
        .iter()
        .map(|e| format!("{{\"name\":\"{}\",\"value\":\"{}\"}}", e.name, e.value))
        .collect();

    // Register task definition
    let mut task_def = format!(
        r#"aws ecs register-task-definition \
  --family {task_name} \
  --requires-compatibilities FARGATE \
  --network-mode awsvpc \
  --cpu 4096 --memory 8192 \
  --container-definitions '[{{
    "name": "gleisner",
    "image": "gleisner-sandbox:latest",
    "essential": true,
    "environment": [{env_json}],
    "logConfiguration": {{
      "logDriver": "awslogs",
      "options": {{
        "awslogs-group": "/ecs/gleisner",
        "awslogs-region": "{region}",
        "awslogs-stream-prefix": "{task_name}"
      }}
    }}
  }}]'"#,
        env_json = env_overrides.join(","),
        region = config.region,
    );

    if let Some(role) = &config.iam_role {
        let _ = write!(task_def, " --task-role-arn {role}");
    }

    commands.push(DeployCommand {
        description: "Register ECS task definition for the gleisner sandbox".to_string(),
        command: task_def,
    });

    // Run the task
    let run_cmd = format!(
        "aws ecs run-task \
         --cluster gleisner \
         --task-definition {task_name} \
         --launch-type FARGATE \
         --network-configuration 'awsvpcConfiguration={{subnets=[\"subnet-default\"],assignPublicIp=\"{public_ip}\"}}'",
        public_ip = if input.report.network.allow_internet {
            "ENABLED"
        } else {
            "DISABLED"
        },
    );

    commands.push(DeployCommand {
        description: "Run the Fargate task".to_string(),
        command: run_cmd,
    });

    commands.push(DeployCommand {
        description: "Wait for the task to complete".to_string(),
        command: format!(
            "aws ecs wait tasks-stopped --cluster gleisner --tasks $(aws ecs list-tasks --cluster gleisner --family {task_name} --query 'taskArns[0]' --output text)"
        ),
    });
}

fn generate_aws_ec2_commands(
    config: &AwsConfig,
    input: &DeployInput<'_>,
    env_vars: &[EnvVar],
    commands: &mut Vec<DeployCommand>,
) {
    let instance_name = format!("gleisner-{}", input.session_id);
    let instance_type = config.instance_type.as_deref().unwrap_or("c6a.xlarge");

    let user_data_vars: String = env_vars
        .iter()
        .map(|e| format!("export {}='{}'", e.name, e.value))
        .collect::<Vec<_>>()
        .join("\n");

    let user_data = format!(
        r#"#!/bin/bash
set -euo pipefail
{user_data_vars}
curl -fsSL https://gleisner.dev/install.sh | bash
aws s3 cp "${{GLEISNER_FORGE_URI}}" /tmp/forge-output.json
gleisner forge --run --from-spec /tmp/forge-output.json
aws s3 cp .gleisner/session-manifest.json "${{GLEISNER_MANIFEST_URI}}"
shutdown -h now"#,
    );

    let mut create_cmd = format!(
        "aws ec2 run-instances \
         --image-id resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.12-x86_64 \
         --instance-type {instance_type} \
         --tag-specifications 'ResourceType=instance,Tags=[{{Key=Name,Value={instance_name}}}]' \
         --user-data '{user_data}'",
    );

    if config.nitro_enclave {
        create_cmd.push_str(" --enclave-options Enabled=true");
    }

    if let Some(role) = &config.iam_role {
        let _ = write!(create_cmd, " --iam-instance-profile Arn={role}");
    }

    if !input.report.network.allow_internet {
        // No public IP = no internet (requires NAT gateway for S3 access via VPC endpoint)
        create_cmd.push_str(" --no-associate-public-ip-address");
    }

    commands.push(DeployCommand {
        description: format!(
            "Launch {} EC2 instance",
            if config.nitro_enclave {
                "Nitro Enclave"
            } else {
                "standard"
            }
        ),
        command: create_cmd,
    });

    commands.push(DeployCommand {
        description: "Wait for instance to finish and retrieve manifest".to_string(),
        command: format!(
            "aws ec2 wait instance-terminated --filters 'Name=tag:Name,Values={instance_name}'"
        ),
    });
}

fn default_gcp_service() -> GcpService {
    GcpService::default()
}

fn default_aws_service() -> AwsService {
    AwsService::default()
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::*;
    use crate::bridge::{BridgeReport, ForgeFilesystemPolicy, ForgeNetworkPolicy};

    fn test_report() -> BridgeReport {
        BridgeReport {
            filesystem: ForgeFilesystemPolicy {
                readonly_bind: vec![PathBuf::from("/usr/lib")],
                readwrite_bind: vec![PathBuf::from("/home/user/.config/app")],
            },
            network: ForgeNetworkPolicy {
                allow_dns: true,
                allow_internet: false,
            },
            credential_paths: vec!["~/.ssh".to_string()],
            warnings: Vec::new(),
        }
    }

    fn test_input<'a>(
        report: &'a BridgeReport,
        forge_json: &'a serde_json::Value,
    ) -> DeployInput<'a> {
        DeployInput {
            forge_json,
            report,
            project_dir: std::path::Path::new("/home/user/project"),
            claude_image: "claude:latest",
            claude_args: &[],
            session_id: "test-session-001",
        }
    }

    #[test]
    fn local_spec_includes_all_binds() {
        let report = test_report();
        let forge_json = serde_json::json!({"test": true});
        let input = test_input(&report, &forge_json);
        let spec = generate_deploy_spec(&DeployTarget::Local, &input);

        // project dir + 1 RO + 1 RW = 3
        assert_eq!(spec.volumes.len(), 3);
        assert!(spec.volumes[0].source.contains("project"));
        assert!(!spec.volumes[0].read_only);
        assert!(spec.volumes[1].read_only); // /usr/lib
        assert!(!spec.volumes[2].read_only); // ~/.config/app
    }

    #[test]
    fn gcp_cloudrun_generates_commands() {
        let report = test_report();
        let forge_json = serde_json::json!({"test": true});
        let input = test_input(&report, &forge_json);
        let target = DeployTarget::Gcp(GcpConfig {
            project: "my-project".to_string(),
            region: "us-central1".to_string(),
            service: GcpService::CloudRun,
            machine_type: None,
            bucket: "my-bucket".to_string(),
            confidential: false,
            service_account: None,
        });

        let spec = generate_deploy_spec(&target, &input);

        assert!(spec.manifest_uri.starts_with("gs://my-bucket/sessions/"));
        assert!(
            spec.commands
                .iter()
                .any(|c| c.command.contains("gcloud run jobs create"))
        );
        assert!(
            spec.commands
                .iter()
                .any(|c| c.command.contains("gcloud run jobs execute"))
        );
        // No internet = no VPC egress
        assert!(
            spec.commands
                .iter()
                .any(|c| c.command.contains("--no-vpc-egress"))
        );
    }

    #[test]
    fn gcp_confidential_vm_adds_sev_snp() {
        let report = test_report();
        let forge_json = serde_json::json!({"test": true});
        let input = test_input(&report, &forge_json);
        let target = DeployTarget::Gcp(GcpConfig {
            project: "my-project".to_string(),
            region: "us-central1".to_string(),
            service: GcpService::ComputeEngine,
            machine_type: Some("n2d-standard-4".to_string()),
            bucket: "my-bucket".to_string(),
            confidential: true,
            service_account: None,
        });

        let spec = generate_deploy_spec(&target, &input);

        assert!(spec.commands.iter().any(|c| c.command.contains("SEV_SNP")));
        assert!(
            spec.commands
                .iter()
                .any(|c| c.description.contains("Confidential"))
        );
    }

    #[test]
    fn aws_fargate_generates_task_definition() {
        let report = test_report();
        let forge_json = serde_json::json!({"test": true});
        let input = test_input(&report, &forge_json);
        let target = DeployTarget::Aws(AwsConfig {
            region: "us-east-1".to_string(),
            service: AwsService::Fargate,
            instance_type: None,
            bucket: "my-bucket".to_string(),
            nitro_enclave: false,
            iam_role: None,
        });

        let spec = generate_deploy_spec(&target, &input);

        assert!(spec.manifest_uri.starts_with("s3://my-bucket/sessions/"));
        assert!(
            spec.commands
                .iter()
                .any(|c| c.command.contains("register-task-definition"))
        );
        assert!(spec.commands.iter().any(|c| c.command.contains("run-task")));
    }

    #[test]
    fn aws_nitro_adds_enclave_option() {
        let report = test_report();
        let forge_json = serde_json::json!({"test": true});
        let input = test_input(&report, &forge_json);
        let target = DeployTarget::Aws(AwsConfig {
            region: "us-east-1".to_string(),
            service: AwsService::Ec2,
            instance_type: Some("c6a.xlarge".to_string()),
            bucket: "my-bucket".to_string(),
            nitro_enclave: true,
            iam_role: Some("arn:aws:iam::123:role/gleisner".to_string()),
        });

        let spec = generate_deploy_spec(&target, &input);

        assert!(
            spec.commands
                .iter()
                .any(|c| c.command.contains("Enabled=true"))
        );
        assert!(
            spec.commands
                .iter()
                .any(|c| c.description.contains("Nitro"))
        );
    }

    #[test]
    fn internet_allowed_affects_network_config() {
        let mut report = test_report();
        report.network.allow_internet = true;
        let forge_json = serde_json::json!({"test": true});
        let input = test_input(&report, &forge_json);

        // GCP: should NOT have --no-vpc-egress
        let gcp_spec = generate_deploy_spec(
            &DeployTarget::Gcp(GcpConfig {
                project: "p".to_string(),
                region: "r".to_string(),
                service: GcpService::CloudRun,
                machine_type: None,
                bucket: "b".to_string(),
                confidential: false,
                service_account: None,
            }),
            &input,
        );
        assert!(
            !gcp_spec
                .commands
                .iter()
                .any(|c| c.command.contains("--no-vpc-egress"))
        );

        // AWS: should have assignPublicIp=ENABLED
        let aws_spec = generate_deploy_spec(
            &DeployTarget::Aws(AwsConfig {
                region: "r".to_string(),
                service: AwsService::Fargate,
                instance_type: None,
                bucket: "b".to_string(),
                nitro_enclave: false,
                iam_role: None,
            }),
            &input,
        );
        assert!(
            aws_spec
                .commands
                .iter()
                .any(|c| c.command.contains("ENABLED"))
        );
    }

    #[test]
    fn deploy_spec_roundtrips_json() {
        let report = test_report();
        let forge_json = serde_json::json!({"test": true});
        let input = test_input(&report, &forge_json);
        let spec = generate_deploy_spec(&DeployTarget::Local, &input);

        let json = serde_json::to_string(&spec).unwrap();
        let roundtripped: DeploySpec = serde_json::from_str(&json).unwrap();

        assert_eq!(spec.manifest_uri, roundtripped.manifest_uri);
        assert_eq!(spec.volumes.len(), roundtripped.volumes.len());
        assert_eq!(spec.commands.len(), roundtripped.commands.len());
    }
}
